# ~/.config/starship.toml

# Inserts a blank line between shell prompts
# ---------------------------------
add_newline = true

# Change command timeout from 500 to 1000 ms
# ---------------------------------
command_timeout = 1000

# Change the default prompt format
# ---------------------------------
# Config #1:
format = """\
[╭╴](242)$env_var $hostname:$shell $all\
[╰─](242)$character"""

# Config #2:
# format = """$env_var $all"""
# [character]
# success_symbol = "[](242)"
# error_symbol = "[](242)"


# Elements in the prompt. Shows an icon that should be included by zshrc script based on the distribution or OS
# ---------------------------------
[env_var.STARSHIP_DISTRO]
format = '[$env_value]($style)'
style = "white"
variable = "STARSHIP_DISTRO"
disabled = false

[shell]
format = "[$indicator]($style)"
style = "bold blue"
unknown_indicator = 'mystery shell'
disabled = false

[hostname]
format = "[$hostname]($style)"
style = "bold yellow"
ssh_only = false
disabled = false

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) @'
disabled = true
show_always = true

[directory]
truncation_length = 1
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
style = "bold green"
truncation_symbol = "…/"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
ahead = "⇡${count}"
behind = "⇣${count}"
staged = '[++\($count\)](green)'
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "🏳"
stashed = " "
renamed = "襁"
deleted = " "
modified = "!${count}"
untracked = "?${count}"

[kubernetes]
format = 'via [ﴱ $context\($namespace\)]($style) '
style = "bold purple"
disabled = false

[terraform]
format = "via [ terraform $version]($style) "
disabled = false

[docker_context]
format = "via [ $context]($style) "
style = "bold blue"
disabled = false

[helm]
format = "via [ $version]($style) "
style = "bold purple"
disabled = false

[python]
symbol = " "
python_binary = "python3"
disabled = false

